<template>
  <v-responsive class="ma-auto overflow-visible" max-width="868px">
    <sectionComponent :item="itemSection">
      <EntryFields :entryFieldsContent="fieldsContent"></EntryFields>
    </sectionComponent>
  </v-responsive>
</template>

<script>
import sectionComponent from '../../sectionComponent.vue'
import EntryFields from '../components/EntryFields.vue'
export default {
  components: { EntryFields, sectionComponent },
  name: 'EntryFieldsVue',
  data() {
    return {
      itemSection: {
        title: 'Zone de saisie',
        description: `The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Ttranslation by
        H. Rackham. Is to create groups of anything that should be controlled by a
        <strong>Sections 1.10.32 and 1.10.33</strong>.`,
        linkGit: 'https://github.com/Flatoupix/eudo-front-app/blob/resume/src/features/components/Summary.vue',
      },
      fieldsContent: {
        title: 'Identification du donateur',
        description:
          'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32',
        fields: [
          {
            Value: 'salut les copains',
            ReadOnly: false,
            Required: false,
            FileId: 13422,
            DescId: 256,
            IsVisible: true,
            HasMidFormula: false,
            HasORMFormula: false,
            Formula: '',
            FldFormat: 1,
            AutoComplete: false,
            IsMainField: false,
            PosX: 1,
            PosY: 20,
            DispOrder: 30,
            Colspan: 1,
            Label: 'Type 1 (ednField) ',
            Format: 1,
            ToolTipText: '',
            ValueColor: '',
            StyleForeColor: '',
            BackgroundColor: '',
            Bold: false,
            Italic: false,
            Flat: false,
            Underline: false,
            LabelHidden: false,
            Width: 0,
            IsSortable: false,
            SortOrder: -1,
            IsFiltrable: false,
            IsComputable: false,
            IsInRules: false,
          },
          {
            DisplayValue: [
              {
                id: 13,
                text: 'D',
              },
            ],
            Value: {
              id: 13,
              text: 'D',
            },
            ReadOnly: false,
            Required: false,
            FileId: 13422,
            DescId: 223,
            IsVisible: true,
            HasMidFormula: false,
            HasORMFormula: false,
            Formula: '',
            FldFormat: 1,
            PopupDescId: 323,
            BoundDescId: 0,
            PopupType: 3,
            Multiple: false,
            IsTree: false,
            IsTreeViewOnlyLastChildren: false,
            EAction: 'LNKDEFAULT',
            PosX: 0,
            PosY: 23,
            DispOrder: 34,
            Colspan: 1,
            Label: 'Type 2 (catalogue)',
            Format: 2,
            ToolTipText: '',
            ValueColor: '#bb1515',
            StyleForeColor: '#404040',
            BackgroundColor: '',
            Bold: false,
            Italic: false,
            Flat: true,
            Underline: false,
            LabelHidden: false,
            Width: 0,
            IsSortable: false,
            SortOrder: -1,
            IsFiltrable: false,
            IsComputable: false,
            IsInRules: false,
            Watermark: 'scoring',
          },
          {
            BackgroundColor: '',
            Bold: false,
            Colspan: 1,
            DescId: 208,
            DispOrder: 5,
            FileId: 3078,
            Flat: true,
            FldFormat: 6,
            Format: 3,
            Formula: '',
            HasMidFormula: false,
            HasORMFormula: false,
            IsComputable: false,
            IsFiltrable: false,
            IsInRules: false,
            IsSortable: false,
            IsVisible: true,
            Italic: true,
            Label: 'Type 3 (email)',
            LabelHidden: false,
            MailStatusEudo: 0,
            MailStatusSubTech: 0,
            MailStatusTech: 0,
            PosX: 1,
            PosY: 3,
            RGPD: {
              CategoryLabel: 'Autre raison 2',
              CategoryType: '1',
              Enabled: true,
              NatureLabel: 'Personnelle',
              NatureType: 0,
            },
            ReadOnly: false,
            Required: false,
            SortOrder: -1,
            StyleForeColor: '#404040',
            ToolTipText: "Courriel de l'adresse principale du contact",
            Underline: false,
            Value: 'grc@eudoweb.com',
            ValueColor: '#c48af2',
            Width: 0,
          },
          {
            BackgroundColor: '',
            Bold: false,
            Colspan: 1,
            DescId: 217,
            DispOrder: 6,
            DisplaySmsBtn: true,
            FileId: 3078,
            Flat: true,
            FldFormat: 12,
            Format: 4,
            Formula: '',
            HasMidFormula: true,
            HasORMFormula: false,
            IsComputable: false,
            IsFiltrable: false,
            IsInRules: false,
            IsSortable: false,
            IsVisible: true,
            Italic: false,
            Label: 'Type 4 (phone)',
            LabelHidden: false,
            PosX: 1,
            PosY: 4,
            RGPD: {
              CategoryLabel: 'Autre motif',
              CategoryType: '1',
              Enabled: true,
              NatureLabel: 'Personnelle',
              NatureType: 0,
            },
            ReadOnly: false,
            Required: false,
            SortOrder: -1,
            StyleForeColor: '',
            ToolTipText: '',
            Underline: false,
            Value: '06 66 66 66 66',
            ValueColor: '',
            Watermark: 'N° de mobile',
            Width: 0,
          },
          {
            Value: 'https://www.linkedin.com/in/',
            ReadOnly: false,
            Required: false,
            FileId: 13422,
            DescId: 206,
            IsVisible: true,
            HasMidFormula: false,
            HasORMFormula: false,
            Formula: '',
            FldFormat: 27,
            RootURL: 'https://www.linkedin.com/in/',
            Icon: 'linkedin-square',
            IconColor: '#1785bf',
            PosX: 1,
            PosY: 10,
            DispOrder: 13,
            Colspan: 1,
            Label: 'Type 6 (social)',
            Format: 6,
            ToolTipText: '',
            ValueColor: '',
            StyleForeColor: '',
            BackgroundColor: '',
            Bold: false,
            Italic: true,
            Flat: false,
            Underline: false,
            LabelHidden: false,
            Width: 0,
            IsSortable: false,
            SortOrder: -1,
            IsFiltrable: false,
            IsComputable: false,
            IsInRules: false,
            Watermark: 'Url Linkedin',
          },
          {
            BackgroundColor: '',
            Bold: false,
            Colspan: 1,
            DescId: 236,
            DispOrder: 45,
            FileId: 3078,
            Flat: false,
            FldFormat: 25,
            Format: 10,
            Formula: '',
            HasMidFormula: false,
            HasORMFormula: false,
            IsComputable: false,
            IsFiltrable: false,
            IsInRules: false,
            IsSortable: false,
            IsVisible: true,
            Italic: false,
            Label: 'Type 10 (Bouton)',
            LabelHidden: false,
            PosX: 0,
            PosY: 29,
            ReadOnly: false,
            Required: false,
            SortOrder: -1,
            StyleForeColor: '',
            ToolTipText: '',
            Underline: false,
            Value: '1',
            ValueColor: '',
            Width: 0,
          },
          {
            Value: 1,
            ReadOnly: false,
            Required: false,
            FileId: 13422,
            DescId: 230,
            IsVisible: true,
            HasMidFormula: false,
            HasORMFormula: false,
            Formula: '',
            FldFormat: 3,
            PosX: 1,
            PosY: 31,
            DispOrder: 50,
            Colspan: 1,
            Label: 'Type 11 (logic)',
            Format: 11,
            ToolTipText: '',
            ValueColor: '',
            StyleForeColor: '       ',
            BackgroundColor: '',
            Bold: false,
            Italic: false,
            Flat: false,
            Underline: false,
            LabelHidden: false,
            Width: 0,
            IsSortable: false,
            SortOrder: -1,
            IsFiltrable: false,
            IsComputable: false,
            IsInRules: true,
          },
          {
            BackgroundColor: '',
            Bold: false,
            Colspan: 1,
            DateEndDescId: -1,
            DateStartDescId: 0,
            DescId: 224,
            DispOrder: 8,
            DisplayFormat: 'D/d/MM/YYYY',
            DisplayValue: '2021-02-22',
            FileId: 3078,
            Flat: false,
            FldFormat: 2,
            Format: 14,
            Formula: '',
            HasMidFormula: false,
            HasORMFormula: false,
            IsComputable: false,
            IsFiltrable: false,
            IsInRules: false,
            IsSortable: false,
            IsVisible: true,
            Italic: false,
            Label: 'Type 14 (Date)',
            LabelHidden: false,
            PosX: 1,
            PosY: 6,
            RGPD: {
              CategoryLabel: 'Opinions politiques',
              CategoryType: '3',
              Enabled: true,
              NatureLabel: 'Sensible',
            },
            ReadOnly: false,
            Required: false,
            SortOrder: -1,
            StyleForeColor: '',
            ToolTipText: '',
            Underline: false,
            Value: '2021-02-22 16:07:00',
            ValueColor: '',
            Width: 0,
          },
          {
            BackgroundColor: '',
            Bold: false,
            Colspan: 1,
            DescId: 242,
            DispOrder: 71,
            FileId: 3078,
            Flat: false,
            FldFormat: 9,
            Format: 17,
            Formula: '',
            HasMidFormula: false,
            HasORMFormula: false,
            IsComputable: false,
            IsFiltrable: false,
            IsHtml: false,
            IsInRules: false,
            IsSortable: false,
            IsVisible: true,
            Italic: false,
            Label: 'Type 17 (Mémo)',
            LabelHidden: false,
            PosX: 1,
            PosY: 45,
            ReadOnly: false,
            Required: false,
            Rowspan: 4,
            SortOrder: -1,
            StyleForeColor: '',
            ToolTipText: '',
            Underline: false,
            Value: 'Hello',
            ValueColor: '',
            Width: 0,
          },
          {
            BackgroundColor: '',
            Bold: false,
            Colspan: 1,
            DescId: 227,
            DispOrder: 39,
            DisplayValue: '',
            FileId: 3078,
            Flat: false,
            FldFormat: 10,
            Format: 18,
            Formula: '',
            HasMidFormula: false,
            HasORMFormula: false,
            IsComputable: false,
            IsFiltrable: false,
            IsInRules: false,
            IsSortable: false,
            IsVisible: true,
            Italic: false,
            Label: 'Type (18) Numérique',
            LabelHidden: false,
            PosX: 0,
            PosY: 26,
            RGPD: {
              CategoryLabel: 'Origine raciale ou ethnique',
              CategoryType: '2',
              Enabled: true,
              NatureLabel: 'Sensible',
              NatureType: 1,
            },
            ReadOnly: true,
            Required: false,
            SortOrder: -1,
            StyleForeColor: '',
            ToolTipText: 'numérique ?',
            Underline: false,
            Value: '156',
            ValueColor: '',
            Width: 0,
          },
          {
            BackgroundColor: '',
            Bold: false,
            Colspan: 1,
            DescId: 248,
            DispOrder: 59,
            FileId: 3078,
            Flat: false,
            FldFormat: 7,
            Format: 23,
            Formula: '',
            HasMidFormula: false,
            HasORMFormula: false,
            IsComputable: false,
            IsFiltrable: false,
            IsInRules: false,
            IsSortable: false,
            IsVisible: true,
            Italic: false,
            Label: 'Type 23 (HyperLink)',
            LabelHidden: false,
            PosX: 0,
            PosY: 36,
            ReadOnly: false,
            Required: false,
            SortOrder: -1,
            StyleForeColor: '',
            ToolTipText: '',
            Underline: false,
            Value: 'https://www.google.fr/',
            ValueColor: '',
            Width: 0,
          },
          {
            BackgroundColor: '',
            Bold: false,
            Colspan: 1,
            DescId: 239,
            DispOrder: 29,
            FileId: 3078,
            Flat: false,
            FldFormat: 11,
            Format: 24,
            Formula: '',
            HasMidFormula: false,
            HasORMFormula: false,
            IsComputable: false,
            IsFiltrable: false,
            IsInRules: false,
            IsSortable: false,
            IsVisible: true,
            Italic: false,
            Label: 'Type 24 (File)',
            LabelHidden: false,
            PosX: 0,
            PosY: 20,
            ReadOnly: false,
            Required: false,
            SortOrder: -1,
            StyleForeColor: '',
            ToolTipText: '',
            Underline: false,
            Value: '',
            ValueColor: '',
            Width: 0,
            WorkDirectory: '[200]',
          },
          {
            BackgroundColor: '',
            Bold: false,
            Colspan: 1,
            DescId: 257,
            DispOrder: 25,
            DisplayValue: [
              {
                id: 10085,
                text: 'BENJAMIN',
              },
              {
                id: 10074,
                text: 'BERTRABD',
              },
              {
                id: 10070,
                text: 'EDN_EXTRANET',
              },
            ],
            Value: [
              {
                id: 10070,
                text: 'EDN_EXTRANET',
              },
            ],
            FileId: 3078,
            Flat: false,
            FldFormat: 8,
            Format: 25,
            Formula: '',
            FullUserList: true,
            HasMidFormula: false,
            HasORMFormula: false,
            IsComputable: false,
            IsFiltrable: false,
            IsInRules: false,
            IsSortable: false,
            IsVisible: true,
            Italic: false,
            Label: 'Type 25 (catalogue multiple "Users" ',
            LabelHidden: false,
            Multiple: true,
            PosX: 1,
            PosY: 17,
            ReadOnly: false,
            Required: false,
            SortOrder: -1,
            StyleForeColor: '',
            ToolTipText: '',
            Underline: false,
            ValueColor: '',
            Width: 0,
          },
        ],
      },
    }
  },
  methods: {},
  mounted() {},
}
</script>
<style lang="stylus"></style>
