<template>
  <v-responsive class="ma-auto overflow-visible" max-width="868px">
    <sectionComponent :item="itemSection">
      <EntryFields :entryFieldsContent="fieldsContent"></EntryFields>
    </sectionComponent>
  </v-responsive>
</template>

<script>
import sectionComponent from '../../sectionComponent.vue'
import EntryFields from '../components/EntryFields.vue'
export default {
  components: { EntryFields, sectionComponent },
  name: 'EntryFieldsVue',
  data() {
    return {
      itemSection: {
        title: 'Zone de saisie',
        description: `The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Ttranslation by
        H. Rackham. Is to create groups of anything that should be controlled by a
        <strong>Sections 1.10.32 and 1.10.33</strong>.`,
        linkGit: 'https://github.com/Flatoupix/eudo-front-app/blob/resume/src/features/components/Summary.vue',
      },

      fieldsContent: {
        title: 'Identification du donateur',
        description:
          'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32',
        fields: [
          {
            Value: 'philippe-leroyeiuzfhoizehjfnzeoijfzeijf,ozie,foiez,foize,fioezfez',
            ReadOnly: false,
            Required: false,
            FileId: 13422,
            DescId: 206,
            IsVisible: true,
            HasMidFormula: false,
            HasORMFormula: false,
            Formula: '',
            FldFormat: 27,
            RootURL: 'https://www.linkedin.com/in/',
            Icon: 'linkedin-square',
            IconColor: '#1785bf',
            PosX: 1,
            PosY: 10,
            DispOrder: 13,
            Colspan: 1,
            Label: 'Linkedin',
            Format: 6,
            ToolTipText: '',
            ValueColor: '',
            StyleForeColor: '',
            BackgroundColor: '',
            Bold: false,
            Italic: true,
            Flat: false,
            Underline: false,
            LabelHidden: false,
            Width: 0,
            IsSortable: false,
            SortOrder: -1,
            IsFiltrable: false,
            IsComputable: false,
            IsInRules: false,
            Watermark: 'Url Linkedin',
          },
          {
            Value: '0',
            ReadOnly: false,
            Required: false,
            FileId: 13422,
            DescId: 230,
            IsVisible: true,
            HasMidFormula: false,
            HasORMFormula: false,
            Formula: '',
            FldFormat: 3,
            PosX: 1,
            PosY: 31,
            DispOrder: 50,
            Colspan: 1,
            Label: 'Test réactivité',
            Format: 11,
            ToolTipText: '',
            ValueColor: '',
            StyleForeColor: '       ',
            BackgroundColor: '',
            Bold: false,
            Italic: false,
            Flat: false,
            Underline: false,
            LabelHidden: false,
            Width: 0,
            IsSortable: false,
            SortOrder: -1,
            IsFiltrable: false,
            IsComputable: false,
            IsInRules: true,
          },
          {
            DisplayValue: 'VIDEO PROJECTEUR 4345',
            Value: '44',
            ReadOnly: false,
            Required: false,
            FileId: 13422,
            DescId: 299,
            IsVisible: true,
            HasMidFormula: false,
            HasORMFormula: false,
            Formula: '',
            FldFormat: 8,
            Multiple: false,
            FullUserList: true,
            PosX: 0,
            PosY: 0,
            DispOrder: 0,
            Colspan: 1,
            Label: 'Appartient à',
            Format: 25,
            ToolTipText: '',
            ValueColor: '',
            StyleForeColor: '',
            BackgroundColor: '',
            Bold: false,
            Italic: false,
            Flat: true,
            Underline: false,
            LabelHidden: false,
            Width: 0,
            IsSortable: false,
            SortOrder: -1,
            IsFiltrable: false,
            IsComputable: false,
            IsInRules: false,
          },
          {
            DisplayValue: 'D',
            Value: '13',
            ReadOnly: false,
            Required: false,
            FileId: 13422,
            DescId: 223,
            IsVisible: true,
            HasMidFormula: false,
            HasORMFormula: false,
            Formula: '',
            FldFormat: 1,
            PopupDescId: 323,
            BoundDescId: 0,
            PopupType: 3,
            Multiple: false,
            IsTree: false,
            IsTreeViewOnlyLastChildren: false,
            EAction: 'LNKDEFAULT',
            PosX: 0,
            PosY: 23,
            DispOrder: 34,
            Colspan: 1,
            Label: 'Scoring',
            Format: 2,
            ToolTipText: '',
            ValueColor: '#bb1515',
            StyleForeColor: '#404040',
            BackgroundColor: '',
            Bold: false,
            Italic: false,
            Flat: true,
            Underline: false,
            LabelHidden: true,
            Width: 0,
            IsSortable: false,
            SortOrder: -1,
            IsFiltrable: false,
            IsComputable: false,
            IsInRules: false,
            Watermark: 'scoring',
          },
          {
            Value: '',
            ReadOnly: false,
            Required: false,
            FileId: 13422,
            DescId: 256,
            IsVisible: true,
            HasMidFormula: false,
            HasORMFormula: false,
            Formula: '',
            FldFormat: 1,
            AutoComplete: false,
            IsMainField: false,
            PosX: 1,
            PosY: 20,
            DispOrder: 30,
            Colspan: 1,
            Label: 'login kha',
            Format: 1,
            ToolTipText: '',
            ValueColor: '',
            StyleForeColor: '',
            BackgroundColor: '',
            Bold: false,
            Italic: false,
            Flat: false,
            Underline: false,
            LabelHidden: false,
            Width: 0,
            IsSortable: false,
            SortOrder: -1,
            IsFiltrable: false,
            IsComputable: false,
            IsInRules: false,
          },
        ],
      },
    }
  },
  methods: {},
  mounted() {},
}
</script>
<style lang="stylus"></style>
